### PR TITLE
Include Pathable's apps and packages dependencies

### PR DESCRIPTION
**Pull request by nachocodoner**
This PR adds and exposes Pathable's dependencies.

- [x] pathable-utilities - https://github.com/pathable/pathable-utilities/pull/78
- [x] pathable-schema - https://github.com/pathable/pathable-schema/pull/73
- [x] pathable-collections - https://github.com/pathable/pathable-collections/pull/93
- [x] pathable-ui - https://github.com/pathable/pathable-ui/pull/230
- [x] pathable-styles - https://github.com/pathable/pathable-styles/pull/35
- [x] pathable-global-styles - https://github.com/pathable/pathable-global-styles/pull/14
- [x] pathable-api - https://github.com/pathable/pathable-api/pull/60
- [x] pathable-app - https://github.com/pathable/pathable-app/pull/50
- [x] pathable-jobs - https://github.com/pathable/pathable-jobs/pull/9
- [x] pathable-mailer - https://github.com/pathable/pathable-mailer/pull/6
- [x] pathable-admin - https://github.com/pathable/pathable-admin/pull/251

Features: [#138164865](https://www.pivotaltracker.com/story/show/138164865)
Needs: https://github.com/pathable/pathable-vendor/pull/1

### CODE REVIEW

**Comment by nachocodoner** [comment]
`-styles` and `-global-styles` don't currently use any dependency from `-vendor`. Therefore I haven't included the reference. Nonetheless some cleaning is tackled in this PR.

**Comment by nachocodoner** [comment]
One question raised when working with `-jobs`. When we import dependencies like [this](https://github.com/pathable/pathable-jobs/blob/master/imports/workers/compile-styles/lib/postcss-modules/index.js#L4) (`dependency/EXPOSED_FILE_PATH`), we need to include it on the app itself. We cannot rely on `pathable-vendor`. I think that can be overcome by using `api.addFiles` for those cases at `-vendor`, but my question is if we use it, are those dependencies be bundled always though they are not ever used?

I am gonna contact MDG for solving that, for the moment I just include those dep cases at app level as well.

**Comment by nachocodoner** [comment]
Ok, I provided a solution for the previous. You can check the example [here](https://github.com/pathable/pathable-jobs/blob/93bb123ae2424af909827ecf3c499250827f0c5b/imports/workers/compile-styles/lib/postcss-modules/index.js#L3).

So if we need to access to a dependency submodule, we can address it by going to the `meteor/pathable-vendor/node_modules/...` path.

**Review by flippyhead — APPROVED** [review]
This is fantastic.

**Pull request merged**
